services:
  builder:
    image: ghcr.io/akibaat/renpy-build:docker
    volumes:
      - ./:/build/renpy
      - build-tmp:/build/tmp
      - root-home:/root
volumes:
  build-tmp:
    name: renpy-build-tmp
  root-home:
    name: renpy-root-home
